INSERT INTO question (question_text, options, correct_answer) VALUES
                                                                  ('What is Java?', 'A programming language,An IDE,A framework,A database', 'A programming language'),
                                                                  ('What is Spring Framework?', 'A Java framework,A database,A programming language,An OS', 'A Java framework'),
                                                                  ('What is Spring Boot?', 'A framework,A database,A language,A server', 'A framework'),
                                                                  ('Which keyword is used to inherit a class in Java?', 'extends,implements,final,static', 'extends'),
                                                                  ('Which collection type allows duplicate elements?', 'Set,Map,List,Queue', 'List'),
                                                                  ('What does JPA stand for?', 'Java Persistent API,Java Processing API,Java Performance API,Java Protocol API', 'Java Persistent API'),
                                                                  ('Which dependency is needed for Spring Data JPA?', 'spring-boot-starter-data-jpa,spring-boot-starter-web,h2,lombok', 'spring-boot-starter-data-jpa'),
                                                                  ('Which annotation is used for mapping a class to a database table?', '@Entity,@Table,@Column,@Repository', '@Entity'),
                                                                  ('Which Spring Boot annotation starts a Spring application?', '@SpringBootApplication,@Component,@Service,@Controller', '@SpringBootApplication'),
                                                                  ('What does REST stand for?', 'Representational State Transfer,Random Engine State Transfer,Remote State Transfer,Representational Safe Transfer', 'Representational State Transfer'),
                                                                  ('Which database is used in-memory in Spring Boot?', 'H2,PostgreSQL,MySQL,Oracle', 'H2'),
                                                                  ('What is the primary purpose of the @Autowired annotation?', 'Dependency injection,Code execution,Service discovery,Request mapping', 'Dependency injection'),
                                                                  ('Which scope is default in a Spring Bean?', 'Singleton,Prototype,Request,Session', 'Singleton'),
                                                                  ('Which component handles HTTP requests in Spring Boot?', 'Controller,Service,Entity,Component', 'Controller'),
                                                                  ('Which file contains the Spring Boot configuration?', 'application.properties,pom.xml,README.md,build.gradle', 'application.properties'),
                                                                  ('What is the use of Spring Boot DevTools?', 'Live reload,Testing,Security,Database Migration', 'Live reload'),
                                                                  ('What is a JPA Repository in Spring?', 'An interface for CRUD operations,A library for UI design,A testing framework,A logging tool', 'An interface for CRUD operations'),
                                                                  ('What is the use of the @Transactional annotation?', 'Manages transactions,Handles exceptions,Validates requests,Sends emails', 'Manages transactions'),
                                                                  ('What is HikariCP in Spring Boot?', 'A connection pool,An ORM framework,An API,A testing tool', 'A connection pool'),
                                                                  ('What is the primary build tool used with Spring Boot?', 'Maven,Gradle,Ant,Jenkins', 'Maven');

INSERT INTO quiz_session (user_id, correct_answers, incorrect_answers) VALUES
                                                                           (101, 0, 0),
                                                                           (102, 0, 0),
                                                                           (103, 0, 0),
                                                                           (104, 0, 0),
                                                                           (105, 0, 0),
                                                                           (106, 0, 0),
                                                                           (107, 0, 0),
                                                                           (108, 0, 0),
                                                                           (109, 0, 0),
                                                                           (110, 0, 0),
                                                                           (111, 0, 0),
                                                                           (112, 0, 0),
                                                                           (113, 0, 0),
                                                                           (114, 0, 0),
                                                                           (115, 0, 0),
                                                                           (116, 0, 0),
                                                                           (117, 0, 0),
                                                                           (118, 0, 0),
                                                                           (119, 0, 0),
                                                                           (120, 0, 0);

